### ISSUE TITLE
C-101EB does not export (only C-101CC)

### ISSUE THREAD

**Issue by Bagger13** [pet333r/pw-dev_script#36]
Modules folder does not include a file for C-101EB version of C-101, only the C-101CC.

I copied "C-101CC.lua" and renamed it "C-101EB" (and updated the comment on line 1), pasted it into the Modules folder, and in a quick check it does export now to DCS UFC.

I did not test with DCS Nav or the AOA app.

**Comment by pet333r** [comment]
I don't have this module, but I will add support in updating the script
