### ISSUE TITLE
[Issue] Various Panel Data not Displaying

### ISSUE THREAD

**Issue by robohunterx** [pet333r/pw-dev_script#4]
The numeric nav data for the KA-50's INU is not displaying. I tried on two different devices, and both devices are working fine for other modules with similar functionality (such as the DED for the F-16 etc) and both have the same issue of not displaying the INU text in the app.

**Comment by pet333r** [comment]
I checked the script, nothing has changed in the application, try to install the script again, maybe you have a typo somewhere in one of the files

**Comment by robohunterx** [comment]
Hey Peter, sorry about the slow response. This is going to be about as detailed as I can muster as to what I've tried. I'm still experiencing the issue with not having data displayed on some panels.


- So I've tried reinstalling the script, which included going over both the text version and video tutorial twice to make sure I'm not missing anything. 
- I've tried allowing both 5160 and 25070 TCP/UDP ports through my computers local firewall, and even shutting the firewall down.
- I double checked that my 2.4ghz network isn't in some weird "isolation mode" on my router, it was not. 
- I triple checked my IP settings in the .config, and setup both my phone and tablet (Both android) and both have the same issue (Hell, the phone is on a 5GHz and 2.4 for the tablet just to make sure that wasn't it or something). Both devices have the identical functionality / issues. 
- My last ditch effort was to manually assign my tablet / phone a static ip via DHCP, which worked fine, but didnt' fix my issues.
- I run DCS in Admin mode if that could be a weird cause

All functionality related to me pressing buttons works just fine! The only issue is some of the data isn't making it to my 


The two photos below is what I'm seeing. 
![20200723_200528](https://user-images.githubusercontent.com/19507632/88350614-a095ad00-cd21-11ea-993c-cde13da1db3a.jpg)
![20200723_200558](https://user-images.githubusercontent.com/19507632/88350620-a1c6da00-cd21-11ea-8965-704316aef0c5.jpg)
As you can see the hornet doesn't show any of the data for the fuel, yet it does show items on the UFC just fine. Other modules work perfectly fine, like the F-16, it displays the DED data no issues whatsoever. There's also some other airframes that work perfectly like the A-10C, and others that partially work such as the KA-50's NAV numbers not displaying correctly.


Here's how I have my configs setup, minus the IP's because...yeah

`-- properties
ExportScript.Config = {}

-- device 1
ExportScript.Config.Export      = true              -- sending data
ExportScript.Config.Export1SD   = false              -- sendind data from SD
ExportScript.Config.Host        = "192.168.x.xxx"     -- IP for 1st app
ExportScript.Config.Port        = 5160              -- port for sending data

-- device 2
ExportScript.Config.Export2     = true              -- sending data
ExportScript.Config.Export2SD   = false              -- sendind data from SD
ExportScript.Config.Host2       = "192.168.x.xxx"     -- IP for 2nd app
ExportScript.Config.Port2       = 5160              -- port for sending data

-- device 3
ExportScript.Config.Export3     = true              -- sending data
ExportScript.Config.Export3SD   = false              -- sendind data from SD
ExportScript.Config.Host3       = "192.168.x.xxx"     -- IP for 3rd app
ExportScript.Config.Port3       = 5160              -- port for sending data

-- device 4
ExportScript.Config.Export4     = true              -- sending data
ExportScript.Config.Export4SD   = false              -- sendind data from SD
ExportScript.Config.Host4       = "127.0.0.1"       -- IP for 3rd app
ExportScript.Config.Port4       = 5160              -- port for sending data

-- receive commands from external apps
ExportScript.Config.Listener         = true         -- listen commands from apps
ExportScript.Config.ListenerPort     = 25070        -- Listener Port receiving commands

-- data separator (do not change)
ExportScript.Config.Separator = ";"

-- Other
ExportScript.Config.ExportInterval         = 0.05	-- export every 0.05 seconds
ExportScript.Config.ExportLowTickInterval  = 0.1	-- export every 0.x seconds
ExportScript.Config.ExportModulePath       = lfs.writedir()..[[Scripts\pw-dev_script\Modules\]]
ExportScript.Config.FirstNewDataSend       = true
ExportScript.Config.FirstNewDataSendCount  = 100

-- data export ( change to true if You are using DCS AoA Indexer )
ExportScript.Config.ExportSelfData          = false     -- export SelfData (Lat, Lon, Alt etc.) every LowTickInterval

-- export Displays data
ExportScript.Config.ExportDisplaysA10C      = true      -- A-10C
ExportScript.Config.ExportDisplaysAV8BNA    = true      -- AV8BNA (UFC, ODU, UVHF)
ExportScript.Config.ExportDisplaysF14B      = true      -- F-14B
ExportScript.Config.ExportDisplaysF16       = true      -- F-16C Viper (DED, CMDS, UHF)
ExportScript.Config.ExportDisplaysFA18      = true      -- F/A-18C (UFC)
ExportScript.Config.ExportDisplaysJF17      = true      -- JF-17 (UFC)
ExportScript.Config.ExportDisplaysM2000     = true      -- Mirage 2000C
ExportScript.Config.ExportDisplaysKA50      = true      -- Ka-50

ExportScript.Config.ExportTWS               = true      -- Threats from FC3

-- if you don't use CDU in A-10C and you want better performance on older devices, change to false
ExportScript.Config.ExportA10C_CDU          = true`

As for my Export.lua, it looks like this (I also use SRS so that's in there as well):
`local lfs=require('lfs'); dofile(lfs.writedir()..[[Scripts\pw-dev_script\Export.lua]])

pcall(function() local dcsSr=require('lfs');dofile(dcsSr.writedir()..[[Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua]]); end,nil);`

This is about as detailed as I can think to get, hopefully it's just something silly I'm overlooking. Loving the program though, thanks for the efforts you've put into it thusfar!

- Robo

**Comment by scortelezzi** [comment]
Hi!

I have the same problem for the Hornet. Brand new install, I just purchased the app yesterday. Follow the instructions from the video, the UFC works perfect (both buttons and information it`s display OK), but for the IFEI the buttons works OK but I have no information displayed.

Let me know if you need any more information/logs/configs.

Thanks!

**Comment by scortelezzi** [comment]
Quick update, I just made a clean reinstall of DCS OpenBeta and the problem remains the same.

Please let me know if you need anything to be tested from my side.

Thanks in advance.

**Comment by pet333r** [comment]
I found a minor error in the script in the Hornet file. Download the file "FA-18C_hornet.lua" and change it in the folder "Modules". Let me know if it helped

**Comment by pet333r** [comment]
> As you can see the hornet doesn't show any of the data for the fuel, yet it does show items on the UFC just fine. Other modules work perfectly fine, like the F-16, it displays the DED data no issues whatsoever. There's also some other airframes that work perfectly like the A-10C, and others that partially work such as the KA-50's NAV numbers not displaying correctly.

> 
> * Robo

Give some screenshots of what it looks like in the Ka-50, maybe I missed something, or I will have to change the font if not everything is displayed as it should

**Comment by robohunterx** [comment]
> Give some screenshots of what it looks like in the Ka-50, maybe I missed something, or I will have to change the font if not everything is displayed as it should

Screen should would basically be the NAV panel in the KA-50 in portrait mode, with no numbers displaying at all. I don't get any data displayed, but the NAV panel does update the lights on the button etc, just no digits. I'd get you a picture of that but I'm traveling for a week or so.

> I found a minor error in the script in the Hornet file. Download the file "FA-18C_hornet.lua" and change it in the folder "Modules". Let me know if it helped

I'll give it a wack when I'm able to. Thanks for the replies.

**Comment by pet333r** [comment]
Update the script, everything should work as it should;-)

**Comment by robohunterx** [comment]
That fixed it! However looks like you moved that page to another one away from the UFC page and replaced it with an RWR panel indicator that's somewhat buggish, but at any rate thanks for helping!
